spring:
  application:
    name: securityDeepLearning

server:
  port: 8080

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.jdbc.core: DEBUG     # Логирование запросов JDBC
    org.hibernate.SQL: DEBUG                 # Логирование SQL-запросов
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: DEBUG