create table users
(
    id                         bigint generated by default as identity,
    password                   varchar(255),
    username                   varchar(255) unique,
    image                      varchar(255),
    is_account_non_expired     boolean not null,
    is_account_non_locked      boolean not null,
    is_credentials_non_expired boolean not null,
    is_enabled                 boolean not null,
    primary key (id)
);

create table user_roles
(
    user_id bigint not null,
    roles   varchar(255) check (roles in ('ROLE_USER', 'ROLE_ADMIN')),
    foreign key (user_id) references users (id)
);
