name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Run tests with Maven
        env:
          oauth2.google.client-id: ${{ secrets.OAUTH2_GOOGLE_CLIENT_ID }}
          oauth2.google.client-secret: ${{ secrets.OAUTH2_GOOGLE_CLIENT_SECRET }}
          # Можно добавить другие переменные, если нужно, например, для БД:
          # DB_URL: ${{ secrets.DB_URL }}
          # DB_USERNAME: ${{ secrets.DB_USERNAME }}
          # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SPRING_PROFILES_ACTIVE: dev
        run: mvn clean package -Pdev -Dmaven.test.skip=false

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-deep-learning
          path: target/*.jar
